create extension if not exists vector;

create table if not exists document_chunks (
  id bigint generated by default as identity primary key,
  source_file text not null,
  content text not null,
  embedding vector(1536) not null,
  metadata jsonb not null default '{}'::jsonb,
  content_hash text not null,
  updated_at timestamptz not null default now(),
  unique (source_file, content_hash)
);

create index if not exists document_chunks_embedding_idx
  on document_chunks using hnsw (embedding vector_cosine_ops);

create or replace function match_document_chunks(
  query_embedding vector(1536),
  match_count int default 5,
  filter jsonb default null
)
returns table (id bigint, source_file text, content text, metadata jsonb, similarity float)
language sql stable
as $$
  select document_chunks.id, document_chunks.source_file, document_chunks.content, document_chunks.metadata,
    1 - (document_chunks.embedding <=> query_embedding) as similarity
  from document_chunks
  where filter is null or document_chunks.metadata @> filter
  order by document_chunks.embedding <=> query_embedding
  limit match_count;
$$;